# Generated by Django 2.2.4 on 2020-07-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ironed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='washed',
            field=models.BooleanField(default=False),
        ),
    ]
