# Generated by Django 2.2.4 on 2020-07-10 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200710_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
